{{- if and .Values.contractToken.value (not .Values.contractToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thunderstorm.contractTokenSecretName" . }}
  labels:
    {{- include "thunderstorm.labels" . | nindent 4 }}
type: Opaque
stringData:
  CONTRACT_TOKEN: {{ .Values.contractToken.value | quote }}
{{- end }}
